/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "circulant.h"


void
circulant_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	myVector  docirculant_1_arg;
	int i,k=1;
	int matSize;
	int myVector[matSize];


#ifndef	DEBUG
	clnt = clnt_create (host, CIRCULANT_PROG, DO_CIRC, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	printf("enter the size of your vector: ");
	scanf("%d", &matSize);
	docirculant_1_arg.vectSize = matSize;
	printf("\n");

	printf("vector from clients is: [");

   	for(i=0; i<matSize; i++)
   	{

      	myVector[i] = k;
      	printf("%d ", myVector[i]);
      	k++;
   	}

   	printf("]\n\n\n");

	result_1 = docirculant_1(&docirculant_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("The circulant was generated succesfully by the server!!!\n");z
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	circulant_prog_1 (host);
exit (0);
}
