/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "circulant.h"

bool_t
xdr_myVector (XDR *xdrs, myVector *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->vectSize))
		 return FALSE;
	return TRUE;
}
